package com.alibaba.qwen.code.runtimebroker.managedworkspace;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.HexFormat;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Pattern;
import org.junit.jupiter.api.Test;

/**
 * Runs the language-neutral W0a fixtures that the TypeScript implementation
 * runs too. The fixtures were generated by an independent implementation of
 * the design document, so both languages are checked against a third one.
 */
class ManagedWorkspaceBindingConformanceTest {
    private static final ObjectMapper JSON = new ObjectMapper();
    private static final Pattern DECIMAL = Pattern.compile("[1-9][0-9]{0,18}");

    @Test
    void pinsTheDigestConstruction() throws IOException {
        JsonNode digest = fixtures().required("digest");

        assertEquals(1, fixtures().required("contractVersion").intValue());
        assertEquals("sha256", digest.required("algorithm").textValue());
        assertEquals("sha256:", digest.required("prefix").textValue());
        assertEquals(ContextBinding.DOMAIN_TAG,
                digest.required("domainTag").textValue());
        List<String> fieldOrder = new ArrayList<>();
        digest.required("fieldOrder").forEach(
                field -> fieldOrder.add(field.textValue()));
        assertEquals(List.of("tenantId", "workspaceId", "workspaceGeneration",
                "storageId", "cwdRelative", "contextConfigRef",
                "contextRevision"), fieldOrder);
    }

    @Test
    void normalizesEverySharedPathCase() throws IOException {
        int valid = 0;
        for (JsonNode fixture : fixtures().required("paths")) {
            String id = fixture.required("id").textValue();
            String input = fixture.required("input").textValue();
            JsonNode expected = fixture.required("expected");
            if (expected.has("cwdRelative")) {
                assertEquals(expected.required("cwdRelative").textValue(),
                        WorkspaceRelativePath.normalize(input), id);
                valid++;
            } else {
                assertEquals("invalid_cwd",
                        expected.required("error").textValue(), id);
                WorkspaceException error = assertThrows(
                        WorkspaceException.class,
                        () -> WorkspaceRelativePath.normalize(input), id);
                assertEquals("invalid_cwd", error.getCode(), id);
            }
        }
        assertTrue(valid > 0);
    }

    @Test
    void encodesAndDigestsEverySharedBindingCase() throws IOException {
        int valid = 0;
        for (JsonNode fixture : fixtures().required("bindings")) {
            String id = fixture.required("id").textValue();
            JsonNode binding = fixture.required("binding");
            JsonNode expected = fixture.required("expected");
            if (expected.has("contextDigest")) {
                ContextBinding built = build(binding);
                assertEquals(expected.required("encodedHex").textValue(),
                        HexFormat.of().formatHex(built.encode()), id);
                assertEquals(expected.required("contextDigest").textValue(),
                        built.getContextDigest(), id);
                valid++;
            } else {
                assertEquals("invalid_binding",
                        expected.required("error").textValue(), id);
                assertThrows(IllegalArgumentException.class,
                        () -> build(binding), id);
            }
        }
        assertTrue(valid > 0);
    }

    @Test
    void acceptsExactlyTheListedCodePointsInEveryProbe() throws IOException {
        JsonNode probes = fixtures().required("probes");
        List<Integer> probed = expand(probes.required("codePoints"));
        Set<Integer> probedSet = new HashSet<>(probed);
        // Read the fixture once per probe: the loop runs for every probed
        // code point, so it stays on plain strings.
        Map<String, String> base = fields(probes.required("binding"));
        for (JsonNode probe : probes.required("cases")) {
            String id = probe.required("id").textValue();
            String template = probe.required("template").textValue();
            String field = probe.required("kind").textValue().equals("path")
                    ? null : probe.required("field").textValue();
            Set<Integer> accepted = new HashSet<>(
                    expand(probe.required("accepted")));
            assertTrue(probedSet.containsAll(accepted), id);
            List<String> mismatches = new ArrayList<>();
            for (int codePoint : probed) {
                String value = template.replace("{c}",
                        new String(Character.toChars(codePoint)));
                String outcome = outcome(field, base, value);
                if (!outcome.equals(accepted.contains(codePoint)
                        ? "accepted" : "rejected")) {
                    mismatches.add("U+" + Integer.toHexString(codePoint)
                            + " " + outcome);
                }
            }
            assertEquals(List.of(), mismatches, id);
        }
    }

    @Test
    void usesEachCaseIdOnce() throws IOException {
        Set<String> ids = new HashSet<>();
        for (JsonNode list : List.of(fixtures().required("paths"),
                fixtures().required("bindings"),
                fixtures().required("probes").required("cases"))) {
            for (JsonNode fixture : list) {
                String id = fixture.required("id").textValue();
                assertTrue(ids.add(id), () -> "duplicate fixture id: " + id);
            }
        }
    }

    /** A null field probes the directory rule; otherwise a binding field. */
    private static String outcome(String field, Map<String, String> base,
            String value) {
        if (field == null) {
            try {
                // Probe templates keep every accepted value in normal form.
                return WorkspaceRelativePath.normalize(value).equals(value)
                        ? "accepted" : "changed";
            } catch (WorkspaceException exception) {
                assertEquals("invalid_cwd", exception.getCode());
                return "rejected";
            }
        }
        Map<String, String> binding = new HashMap<>(base);
        binding.put(field, value);
        try {
            build(binding);
            return "accepted";
        } catch (IllegalArgumentException exception) {
            return "rejected";
        }
    }

    /** Inclusive ranges, which must be ascending and disjoint. */
    private static List<Integer> expand(JsonNode ranges) {
        List<Integer> codePoints = new ArrayList<>();
        for (JsonNode range : ranges) {
            assertTrue(range.isArray() && range.size() == 2
                    && range.get(0).isInt() && range.get(1).isInt(),
                    () -> "a probe range is two integers: " + range);
            int low = range.get(0).intValue();
            int high = range.get(1).intValue();
            assertTrue(low <= high && (codePoints.isEmpty()
                    || low > codePoints.get(codePoints.size() - 1)),
                    () -> "probe ranges must be ascending: " + range);
            for (int codePoint = low; codePoint <= high; codePoint++) {
                codePoints.add(codePoint);
            }
        }
        return codePoints;
    }

    // Java carries generations and revisions as long, so a non-canonical
    // decimal cannot reach ContextBinding; reject it where the wire text is
    // parsed, exactly as a wire decoder would.
    private static ContextBinding build(JsonNode binding) {
        return build(fields(binding));
    }

    private static ContextBinding build(Map<String, String> binding) {
        return new ContextBinding(binding.get("tenantId"),
                binding.get("workspaceId"),
                decimal(binding.get("workspaceGeneration")),
                binding.get("storageId"), binding.get("cwdRelative"),
                binding.get("contextConfigRef"),
                decimal(binding.get("contextRevision")));
    }

    /** The text fields of a fixture binding; a non-text value maps to null. */
    private static Map<String, String> fields(JsonNode binding) {
        Map<String, String> fields = new HashMap<>();
        for (Map.Entry<String, JsonNode> field : binding.properties()) {
            fields.put(field.getKey(), field.getValue().textValue());
        }
        return fields;
    }

    private static long decimal(String value) {
        if (value == null || !DECIMAL.matcher(value).matches()) {
            throw new IllegalArgumentException("not a canonical decimal");
        }
        try {
            return Long.parseLong(value);
        } catch (NumberFormatException exception) {
            throw new IllegalArgumentException("decimal exceeds 64 bits",
                    exception);
        }
    }

    private static JsonNode fixtures() throws IOException {
        Path path = contractDirectory().resolve(
                "managed-workspace-binding-v1.fixtures.json");
        assertTrue(Files.isRegularFile(path),
                () -> "missing shared contract: " + path);
        return JSON.readTree(path.toFile());
    }

    private static Path contractDirectory() {
        Path current = Path.of(System.getProperty("user.dir")).toAbsolutePath();
        for (int depth = 0; depth < 6 && current != null; depth++) {
            Path candidate = current.resolve(Path.of("packages", "cli", "src",
                    "serve", "contracts"));
            if (Files.isDirectory(candidate)) {
                return candidate;
            }
            current = current.getParent();
        }
        throw new AssertionError("cannot locate the shared contract fixtures");
    }
}
